version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/app
